"use client";
/* eslint-disable @next/next/no-img-element -- vinext beta hydrates next/image incorrectly in this interactive client surface */
/* eslint-disable react-hooks/purity -- delivery minimums are intentionally calculated from the visitor's current local date */
/* eslint-disable react-hooks/set-state-in-effect -- browser storage and URL state are restored after hydration */
/* eslint-disable jsx-a11y/label-has-associated-control -- controls are nested directly inside their visible labels */

import { AnchorHTMLAttributes, createContext, FormEvent, MouseEvent as ReactMouseEvent, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import { business, categories, faqs, money, occasions, Product, products } from "./data";

function Image({src,alt,priority=false}:{src:string;alt:string;fill?:boolean;sizes?:string;priority?:boolean}){return <img src={src} alt={alt} width="900" height="1000" loading={priority?"eager":"lazy"} fetchPriority={priority?"high":"auto"}/>}

type RequestItem = { id:string; quantity:number; size:string; note?:string };
const basketKey = "petal-parcel-order-request";
const waBase = `https://wa.me/${business.whatsapp}`;

function whatsapp(message:string){ return `${waBase}?text=${encodeURIComponent(message)}`; }
function hardNavigate(event:ReactMouseEvent<HTMLAnchorElement>){if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();window.location.assign(event.currentTarget.href)}
function Link({onClick,...props}:AnchorHTMLAttributes<HTMLAnchorElement>&{href:string;children:ReactNode}){return <a {...props} onClick={event=>{onClick?.(event);if(!event.defaultPrevented)hardNavigate(event)}}/>}
function addToRequestAndOpen(id:string,size?:string){const chosen=size||products.find(p=>p.id===id)?.sizes[0]||"Standard";let basket:RequestItem[]=[];try{basket=JSON.parse(localStorage.getItem(basketKey)||"[]")}catch{/* Start a fresh device-local request if stored data is malformed. */}const found=basket.find(item=>item.id===id&&item.size===chosen);const next=found?basket.map(item=>item===found?{...item,quantity:item.quantity+1}:item):[...basket,{id,quantity:1,size:chosen}];localStorage.setItem(basketKey,JSON.stringify(next));window.location.assign("/order")}

type BasketUpdate=RequestItem[]|((p:RequestItem[])=>RequestItem[]);
type BasketApi={basket:RequestItem[];ready:boolean;setBasket:(v:BasketUpdate)=>void;add:(id:string,size?:string)=>void};
const BasketContext=createContext<BasketApi>({basket:[],ready:false,setBasket:()=>{},add:()=>{}});
function useBasket(){return useContext(BasketContext)}
export function StoreProvider({children}:{children:ReactNode}){const [basket,setBasketState]=useState<RequestItem[]>([]);const [ready,setReady]=useState(false);useEffect(()=>{try{setBasketState(JSON.parse(localStorage.getItem(basketKey)||"[]"))}catch{/* Ignore malformed device-local demo data. */}setReady(true)},[]);function setBasket(update:BasketUpdate){setBasketState(previous=>{const next=typeof update==="function"?update(previous):update;localStorage.setItem(basketKey,JSON.stringify(next));return next})}function add(id:string,size?:string){addToRequestAndOpen(id,size)}return <BasketContext.Provider value={{basket,ready,setBasket,add}}>{children}</BasketContext.Provider>}

export function Mark(){ return <span className="mark" aria-hidden="true"><i>p</i></span>; }

export function Shell({children}:{children:ReactNode}){
  const [menu,setMenu]=useState(false); const {basket,ready}=useBasket();
  const count=basket.reduce((n,x)=>n+x.quantity,0);
  return <>
    <a className="skip" href="#main">Skip to content</a>
    <div className="announce">Selected gifts may be available for same-day Ahmedabad delivery · <a href="/contact#availability">Check availability</a></div>
    <header className="site-header"><div className="wrap nav-row">
      <Link className="brand" href="/" aria-label={`${business.name} home`}><Mark/><span><b>Petal <em>&</em> Parcel</b><small>flowers · gifts · moments</small></span></Link>
      <button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button>
      <nav className={menu?"nav open":"nav"} aria-label="Primary navigation">
        <a href="/shop" onClick={hardNavigate}>Shop</a><a href="/flowers" onClick={hardNavigate}>Flowers</a><a href="/gift-hampers" onClick={hardNavigate}>Gift Hampers</a><a href="/personalised-gifts" onClick={hardNavigate}>Personalised</a><a href="/occasions" onClick={hardNavigate}>Occasions</a><a href="/corporate" onClick={hardNavigate}>Corporate</a><a href="/about" onClick={hardNavigate}>About</a>
      </nav>
      <div className="nav-actions"><a className="request-link" href="/order" aria-label={`Open request bag with ${ready?count:0} items`}><span className="request-label">Request bag</span><span className="request-count" aria-hidden="true">{ready?count:0}</span></a><a className="button small" target="_blank" rel="noreferrer" href={whatsapp("Hello Petal & Parcel, I would like help choosing a flower or gift.")}>WhatsApp</a></div>
    </div></header>
    <main id="main">{children}</main>
    <footer><div className="wrap footer-grid"><div><Link className="brand inverse footer-brand" href="/"><span><b>Petal <em>&</em> Parcel</b><small>flowers · gifts · moments</small></span></Link><p>{business.tagline}</p><p className="demo-note">Fictional portfolio demonstration. Products, policies and contact details are sample content for adaptation by a real business.</p></div><div><h3>Shop</h3><Link href="/flowers">Fresh flowers</Link><Link href="/gift-hampers">Gift hampers</Link><Link href="/personalised-gifts">Personalised gifts</Link><Link href="/corporate">Corporate gifting</Link></div><div><h3>Visit & contact</h3><p>{business.address}</p><a href={`tel:${business.phone.replace(/\s/g,"")}`}>{business.phone}</a><a href={`mailto:${business.email}`}>{business.email}</a><p>{business.hours}</p></div><div><h3>Helpful links</h3><Link href="/custom-gift">Build a custom gift</Link><Link href="/contact">Delivery information</Link><Link href="/order">Order request</Link><Link href="/contact#policies">Order & delivery policy</Link></div></div><div className="wrap footer-bottom"><span>© 2026 Petal & Parcel · Ahmedabad concept</span><span>Privacy · Sample policies · Instagram</span></div></footer>
    <div className="mobile-dock"><a href={`tel:${business.phone.replace(/\s/g,"")}`}>Call</a><a href={waBase} target="_blank" rel="noreferrer">WhatsApp</a><Link href="/order">Request ({ready?count:0})</Link></div>
  </>;
}

export function SectionHead({eyebrow,title,copy,center=false}:{eyebrow?:string;title:string;copy?:string;center?:boolean}){return <div className={`section-head ${center?"center":""}`}>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}

export function ProductCard({product}:{product:Product}){return <article className="product-card"><Link className="product-image" href={`/products/${product.slug}`}><img src={product.image} alt={`${product.name} arranged for gifting`} width="600" height="660" loading="lazy"/><span>{product.badge}</span></Link><div className="product-copy"><p>{product.type}</p><h3><Link href={`/products/${product.slug}`}>{product.name}</Link></h3><div className="card-meta"><strong>{product.starting?"From ":""}{money(product.price)}</strong>{product.sameDay&&<small>Same-day request</small>}</div><div className="card-actions"><Link href={`/products/${product.slug}`}>View product</Link><button onClick={()=>addToRequestAndOpen(product.id)}>+ Add to request</button></div></div></article>}

export function ProductGrid({items=products}:{items?:Product[]}){return <div className="product-grid">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div>}

export function HomePage(){return <Shell>
  <section className="hero"><div className="wrap hero-grid"><div className="hero-copy"><span className="eyebrow">Made with care in Ahmedabad</span><h1>Thoughtful flowers and gifts for <em>every little celebration.</em></h1><p>Fresh bouquets, curated hampers and personalised keepsakes for birthdays, anniversaries, festivals and everyday surprises.</p><div className="hero-actions"><Link className="button" href="/shop">Shop gifts <span>→</span></Link><a className="button ghost" href={whatsapp("Hello Petal & Parcel, I would like to order a thoughtful gift in Ahmedabad.")} target="_blank" rel="noreferrer">Order on WhatsApp</a></div><p className="delivery-note">Ahmedabad local delivery · Availability and final amount confirmed personally</p></div><div className="hero-collage"><div className="hero-main"><img src={products[0].image} alt="Blush rose bouquet wrapped for gifting" width="900" height="1050" fetchPriority="high"/></div><div className="hero-small"><img src={products[2].image} alt="Curated chocolate celebration hamper" width="400" height="480" fetchPriority="high"/></div><div className="hero-tag">Same-day<br/><strong>requests</strong><small>before {business.cutOff}</small></div></div></div></section>
  <section className="trust-bar"><div className="wrap"><span>✿ Thoughtfully arranged</span><span>⌂ Ahmedabad delivery</span><span>♡ Personal messages</span><span>♢ Custom budgets</span></div></section>
  <section className="section"><div className="wrap"><SectionHead eyebrow="Shop by occasion" title="A lovely answer for every moment" copy="Start with the celebration—we’ll help you shape the rest."/><div className="occasion-grid">{occasions.map((o,i)=><Link href={`/shop?occasion=${encodeURIComponent(o)}`} key={o}><span>{["🎂","♡","✦","❦","☼","✿","◈","◇"][i]}</span><b>{o}</b><small>Explore gifts →</small></Link>)}</div></div></section>
  <section className="section tint"><div className="wrap"><SectionHead eyebrow="Most-loved gifts" title="Made to make their day" copy="Ready-to-personalise favourites for thoughtful, beautifully presented gifting."/><ProductGrid items={products.filter(p=>p.featured).slice(0,8)}/><div className="center-action"><Link className="button ghost dark" href="/shop">See all gifts</Link></div></div></section>
  <section className="section custom-banner"><div className="wrap custom-grid"><div><span className="eyebrow light">Your idea, beautifully packed</span><h2>Build a gift that feels just like them.</h2><p>Choose the occasion, recipient, budget and mood. We’ll turn your preferences into a bouquet or hamper proposal.</p><Link className="button light-button" href="/custom-gift">Build a custom gift →</Link></div><div className="gift-list"><span>01</span><p><b>Tell us the moment</b>Birthday, celebration or simply because.</p><span>02</span><p><b>Choose a budget</b>We curate the contents around you.</p><span>03</span><p><b>Add their personality</b>Colours, flavours and keepsakes they love.</p></div></div></section>
  <section className="section"><div className="wrap"><SectionHead eyebrow="Simple ordering" title="From your screen to their doorstep"/><div className="steps">{[["01","Choose a product","Browse ready ideas or build something custom."],["02","Share the details","Tell us date, area and personalisation."],["03","Confirm together","We confirm availability, delivery and final amount."],["04","Complete payment","Pay only after the shop confirms your request."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><p className="honest-note">Website actions create an order request—not a confirmed order.</p></div></section>
  <section className="section editorial"><div className="wrap editorial-grid"><div className="editorial-image"><img src={products[6].image} alt="Premium anniversary flowers and gift arrangement" width="900" height="1000" loading="lazy"/></div><div><span className="eyebrow">Featured collection</span><h2>Small gestures.<br/>Big anniversary feelings.</h2><p>Romantic flowers, memory-filled keepsakes and indulgent hampers curated for celebrating the two of you.</p><Link className="text-link" href="/shop?occasion=Anniversary">Explore anniversary gifts →</Link></div></div></section>
  <section className="section tint"><div className="wrap two-col"><div><SectionHead eyebrow="Delivery, made clear" title="Local delivery with a human confirmation" copy="We serve selected Ahmedabad neighbourhoods. Charges and timing depend on route, date and product preparation."/><ul className="check-list"><li>Same-day requests for selected products before {business.cutOff}</li><li>Indicative coverage: {business.areas.slice(0,6).join(", ")}</li><li>Recipient availability is recommended for successful delivery</li><li>Seasonal flowers may need a close, approved substitution</li></ul><Link className="text-link delivery-link" href="/contact#availability">Check delivery availability →</Link></div><div><SectionHead eyebrow="Helpful answers" title="Before you send a surprise"/><FAQ items={faqs.slice(0,5)}/></div></div></section>
  <FinalCTA/>
  </Shell>}

export function CatalogPage({preset,title="All flowers & gifts",copy="Search the full collection and narrow it by occasion, budget or availability."}:{preset?:string;title?:string;copy?:string}){const [query,setQuery]=useState("");const [category,setCategory]=useState(preset||"All");const [occasion,setOccasion]=useState("All");const [budget,setBudget]=useState("All");const [same,setSame]=useState(false);const [personal,setPersonal]=useState(false);const [sort,setSort]=useState("featured");
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("occasion");if(requested&&occasions.includes(requested))setOccasion(requested)},[]);
 const filtered=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())&&(category==="All"||p.category===category)&&(occasion==="All"||p.occasions.includes(occasion))&&(budget==="All"||(budget==="under500"?p.price<500:budget==="500-1000"?p.price>=500&&p.price<=1000:budget==="1000-2000"?p.price>1000&&p.price<=2000:budget==="2000-3500"?p.price>2000&&p.price<=3500:p.price>3500))&&(!same||p.sameDay)&&(!personal||p.personalised)).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:Number(b.featured)-Number(a.featured)),[query,category,occasion,budget,same,personal,sort]);
 const clear=()=>{setQuery("");setCategory(preset||"All");setOccasion("All");setBudget("All");setSame(false);setPersonal(false)};
 return <Shell><PageHero eyebrow="The Petal & Parcel edit" title={title} copy={copy}/><section className="section shop-section"><div className="wrap shop-layout"><aside className="filters"><div className="filter-top"><h2>Filter gifts</h2><button onClick={clear}>Clear all</button></div><label>Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bouquet, hamper, plant…"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Occasion<select value={occasion} onChange={e=>setOccasion(e.target.value)}><option>All</option>{occasions.map(x=><option key={x}>{x}</option>)}</select></label><label>Budget<select value={budget} onChange={e=>setBudget(e.target.value)}><option value="All">All budgets</option><option value="under500">Under ₹500</option><option value="500-1000">₹500–₹1,000</option><option value="1000-2000">₹1,000–₹2,000</option><option value="2000-3500">₹2,000–₹3,500</option><option value="above3500">Above ₹3,500</option></select></label><label className="check"><input type="checkbox" checked={same} onChange={e=>setSame(e.target.checked)}/> Same-day request</label><label className="check"><input type="checkbox" checked={personal} onChange={e=>setPersonal(e.target.checked)}/> Personalisation</label></aside><div className="catalog"><div className="results"><p><b>{filtered.length}</b> gifts found</p><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>{filtered.length?<ProductGrid items={filtered}/>:<div className="empty"><span>✿</span><h2>No perfect match yet</h2><p>Try clearing a filter or tell us what you have in mind.</p><button className="button" onClick={clear}>Clear filters</button></div>}</div></div></section><FinalCTA/></Shell>}

export function ProductPage({product}:{product:Product}){const {add}=useBasket();const [size,setSize]=useState(product.sizes[0]);const [qty,setQty]=useState(1);const [message,setMessage]=useState("");const [date,setDate]=useState("");const [area,setArea]=useState("");const min=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().split("T")[0];const direct=`Hello Petal & Parcel,\n\nI would like to check availability for:\nProduct: ${product.name}\nSize: ${size}\nQuantity: ${qty}\nDelivery date: ${date||"To be discussed"}\nDelivery area: ${area||"To be discussed"}\nGift message: ${message||"None yet"}\n\nPlease confirm availability, delivery charge and final amount. Thank you.`;
 return <Shell><section className="section product-detail"><div className="wrap product-detail-grid"><div className="detail-image"><Image src={product.image} alt={`${product.name}: ${product.description}`} fill priority sizes="(max-width: 800px) 100vw, 50vw"/><span>{product.badge}</span></div><div className="detail-copy"><Link className="back" href="/shop">← Back to all gifts</Link><p className="eyebrow">{product.category} · {product.type}</p><h1>{product.name}</h1><p className="detail-price">{product.starting?"Starting from ":""}{money(product.price)}</p><p>{product.description}</p><div className="choice"><label>Choose size or variant<select value={size} onChange={e=>setSize(e.target.value)}>{product.sizes.map(s=><option key={s}>{s}</option>)}</select></label><label>Quantity<div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))} aria-label="Decrease quantity">−</button><span>{qty}</span><button onClick={()=>setQty(Math.min(20,qty+1))} aria-label="Increase quantity">+</button></div></label></div><label>Personal gift message<textarea value={message} maxLength={180} onChange={e=>setMessage(e.target.value)} placeholder="Write a short message for the card…"/></label><div className="choice"><label>Preferred delivery date<input type="date" min={min} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Ahmedabad area or postcode<input value={area} onChange={e=>setArea(e.target.value)} placeholder="e.g. Satellite, 380015"/></label></div><div className="detail-actions"><button className="button" onClick={()=>{for(let i=0;i<qty;i++)add(product.id,size)}}>Add to order request</button><a className="button ghost dark" href={whatsapp(direct)} target="_blank" rel="noreferrer">Order on WhatsApp</a></div><p className="fine-print">Actual flower shades and arrangement may vary slightly with seasonal availability. Any major substitution should be confirmed with you.</p></div></div></section><section className="section tint"><div className="wrap product-info"><div><h2>What’s included</h2><ul className="check-list">{product.included.map(x=><li key={x}>{x}</li>)}</ul></div><div><h2>{product.care?"Care instructions":"Customisation"}</h2><p>{product.care||"Share your preferred colours, packaging and message. We will confirm what is possible before payment."}</p><h3>Availability</h3><p>{product.sameDay?"This product can be requested for same-day preparation on selected dates.":"Please allow time for sourcing and personalisation."}</p></div></div></section><section className="section"><div className="wrap"><SectionHead eyebrow="You may also like" title="Keep the thought going"/><ProductGrid items={products.filter(p=>p.id!==product.id&&(p.category===product.category||p.occasions.some(o=>product.occasions.includes(o)))).slice(0,4)}/></div></section></Shell>}

export function OrderPage(){const {basket,setBasket}=useBasket();const [name,setName]=useState("");const [area,setArea]=useState("");const [date,setDate]=useState("");const [message,setMessage]=useState("");const min=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().split("T")[0];const rows=basket.map(i=>({...i,product:products.find(p=>p.id===i.id)!})).filter(x=>x.product);const subtotal=rows.reduce((n,x)=>n+x.product.price*x.quantity,0);const summary=`Hello Petal & Parcel,\n\nI would like to check availability for this order request:\n\n${rows.map(x=>`${x.product.name}\nSize: ${x.size}\nQuantity: ${x.quantity}\nEstimate: ${money(x.product.price*x.quantity)}`).join("\n\n")}\n\nEstimated subtotal: ${money(subtotal)}\nCustomer: ${name||"Not added"}\nPreferred date: ${date||"To be discussed"}\nDelivery area: ${area||"To be discussed"}\nGift message / notes: ${message||"None"}\n\nPlease confirm availability, delivery charge and final amount. Thank you.`;
 return <Shell><PageHero eyebrow="Your request bag" title="Bring all the lovely details together" copy="Update quantities, add delivery preferences, then send one clear enquiry to the shop."/><section className="section"><div className="wrap order-layout"><div>{rows.length?rows.map(x=><article className="request-item" key={`${x.id}-${x.size}`}><div className="request-thumb"><Image src={x.product.image} alt="" fill sizes="100px"/></div><div><h3>{x.product.name}</h3><p>{x.size}</p><button onClick={()=>setBasket(basket.filter(i=>i!==x))}>Remove</button></div><div className="qty"><button onClick={()=>setBasket(basket.map(i=>i===x?{...i,quantity:Math.max(1,i.quantity-1)}:i))}>−</button><span>{x.quantity}</span><button onClick={()=>setBasket(basket.map(i=>i===x?{...i,quantity:Math.min(20,i.quantity+1)}:i))}>+</button></div><strong>{money(x.product.price*x.quantity)}</strong></article>):<div className="empty"><span>✿</span><h2>Your request bag is waiting</h2><p>Add a bouquet, hamper or keepsake and it will stay here while you browse.</p><Link className="button" href="/shop">Explore gifts</Link></div>}</div>{rows.length>0&&<aside className="order-summary"><h2>Enquiry details</h2><label>Your name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Preferred delivery date<input type="date" min={min} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Delivery area<input value={area} onChange={e=>setArea(e.target.value)} placeholder="Area or postcode"/></label><label>Gift message or notes<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={4}/></label><div className="subtotal"><span>Estimated subtotal</span><strong>{money(subtotal)}</strong></div><p>This is an estimated order request. Availability, delivery charges and the final total will be confirmed by the shop.</p><a className="button full" href={whatsapp(summary)} target="_blank" rel="noreferrer">Send request on WhatsApp</a><Link className="continue" href="/shop">← Continue browsing</Link></aside>}</div></section></Shell>}

export function CustomGiftPage(){return <Shell><PageHero eyebrow="Made around them" title="Build a custom bouquet or gift" copy="Six quick choices give us enough to create a thoughtful first proposal—without asking for unnecessary personal details."/><section className="section"><div className="wrap narrow"><SmartForm kind="custom"/></div></section><section className="section tint"><div className="wrap form-split"><div><SectionHead eyebrow="Flowers, your way" title="Request a custom bouquet" copy="Share the flowers, colours, scale and budget you have in mind. A reference image can guide the style, but is not uploaded permanently in this demo."/><ul className="check-list"><li>Seasonal flower and colour guidance</li><li>Budget-led bouquet sizing</li><li>Gift message and delivery preferences</li></ul></div><SmartForm kind="flower"/></div></section></Shell>}
export function CorporatePage(){return <Shell><PageHero eyebrow="Corporate gifting" title="Gifts that carry your appreciation well" copy="Employee welcomes, festival hampers, client thank-yous and event kits—planned with reliable presentation and room for your brand."/><section className="section"><div className="wrap"><div className="service-grid">{[["Employee welcome kits","Useful desk essentials, stationery and treats in a branded box."],["Festival hampers","Flexible festive edits for teams, clients and partners."],["Client appreciation","Polished gifts with personalised notes and premium packaging."],["Events & conferences","Delegate kits, speaker gifts and coordinated multi-location packing."],["Bulk personalisation","Names, sleeve cards, logo tags and selected branded products."],["Delivery coordination","One Ahmedabad location or an organised list of recipients."]].map(x=><article key={x[0]}><span>◇</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section><section className="section tint"><div className="wrap form-split"><div><SectionHead eyebrow="Request a proposal" title="Tell us the scale. We’ll shape the gift." copy="Volume-based pricing depends on contents, branding, packaging and delivery coordination. Sample minimum order: 20 gifts."/><ul className="check-list"><li>Logo cards, sleeves and selected product branding</li><li>Budget-led curation with samples before bulk production</li><li>Custom packaging and recipient-message coordination</li></ul></div><SmartForm kind="corporate"/></div></section></Shell>}
export function AboutPage(){return <Shell><PageHero eyebrow="Our little story" title="Gifting should feel personal, even on a busy day" copy="Petal & Parcel is a fictional Ahmedabad studio concept built around one idea: make thoughtful gifting easier without making it feel generic."/><section className="section"><div className="wrap editorial-grid"><div className="about-art"><span>Petal</span><i>&</i><span>Parcel</span><small>Ahmedabad · Since someday soon</small></div><div><SectionHead eyebrow="Thoughtful by design" title="A florist’s eye. A gift-giver’s heart."/><p>We imagine each bouquet and hamper as a small story: who it is for, what the moment means, and how it should feel when the ribbon comes undone.</p><p>This portfolio concept is ready to adapt for a real flower shop, hamper maker or personalised-gifting studio. Product data, policies and contact details live centrally for easy updates.</p><div className="values"><b>Warm, never fussy</b><b>Clear about availability</b><b>Flexible with budgets</b><b>Local and personal</b></div></div></div></section><FinalCTA/></Shell>}
export function ContactPage(){return <Shell><PageHero eyebrow="Visit, call or message" title="Let’s make their moment beautiful" copy="Ask about delivery, share a custom idea or get help choosing a gift for someone in Ahmedabad."/><section className="section"><div className="wrap contact-grid"><div className="contact-card"><h2>Petal & Parcel</h2><p>{business.address}</p><p><b>Landmark</b><br/>Near Vijay Cross Road, beside the metro entrance</p><p><b>Opening hours</b><br/>{business.hours}</p><a href={`tel:${business.phone.replace(/\s/g,"")}`}>{business.phone}</a><a href={waBase} target="_blank" rel="noreferrer">WhatsApp the shop</a><a href={`mailto:${business.email}`}>{business.email}</a><a className="button" href="https://maps.google.com/?q=Vijay+Cross+Road+Ahmedabad" target="_blank" rel="noreferrer">Get directions</a></div><SmartForm kind="contact"/></div></section><section id="availability" className="section tint"><div className="wrap form-split"><div><SectionHead eyebrow="Delivery availability" title="Check your area and preferred date" copy="This sends an honest enquiry; it does not show false real-time stock or delivery capacity."/><p>Indicative areas: {business.areas.join(", ")}. Other Ahmedabad locations may be possible with an adjusted delivery charge.</p></div><SmartForm kind="delivery"/></div></section><section id="policies" className="section"><div className="wrap narrow"><SectionHead eyebrow="Sample delivery policy" title="The useful details, kept readable"/><FAQ items={faqs}/></div></section></Shell>}
export function OccasionsPage(){return <Shell><PageHero eyebrow="Start with the moment" title="Gifts for all the reasons you care" copy="Choose an occasion to see flowers, hampers and personalised keepsakes that fit the feeling."/><section className="section"><div className="wrap"><div className="occasion-grid large">{occasions.map((o,i)=><Link href={`/shop?occasion=${encodeURIComponent(o)}`} key={o}><span>{["🎂","♡","✦","❦","☼","✿","◈","◇"][i]}</span><b>{o}</b><small>Browse the collection →</small></Link>)}</div></div></section><FinalCTA/></Shell>}

type FormKind="custom"|"flower"|"corporate"|"contact"|"delivery";
function SmartForm({kind}:{kind:FormKind}){const [step,setStep]=useState(0);const [status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle");const [errors,setErrors]=useState<Record<string,string>>({});const [data,setData]=useState<Record<string,string>>({});const multi=kind==="custom";const fields=kind==="corporate"?[["name","Full name","text"],["company","Company name","text"],["email","Work email","email"],["phone","Mobile number","tel"],["count","Number of gifts","number"],["budget","Budget per gift","text"],["occasion","Occasion","text"],["date","Required delivery date","date"],["locations","Delivery location(s)","text"],["branding","Branding required?","select"],["preferences","Product preferences and message","textarea"],["reference","Logo or brief (optional)","file"]]:kind==="flower"?[["name","Customer name","text"],["phone","Mobile number","tel"],["occasion","Occasion","text"],["flowers","Flower preference","text"],["colours","Preferred colours","text"],["size","Bouquet size","select"],["budget","Budget","text"],["date","Delivery date","date"],["area","Delivery area","text"],["message","Gift message","textarea"],["reference","Reference image (optional)","file"],["instructions","Special instructions","textarea"]]:kind==="contact"?[["name","Full name","text"],["phone","Mobile number","tel"],["email","Email (optional)","email"],["message","How can we help?","textarea"]]:[["area","Ahmedabad area or postcode","text"],["date","Requested date","date"],["product","Product or category","text"],["same","Same-day request?","select"],["phone","Mobile number","tel"]];
 const customSteps=[["occasion","What is the occasion?",occasions.concat("Other")],["recipient","Who is it for?",["Partner","Friend","Parent","Child","Colleague","Client","Employee","Other"]],["budget","What is your budget?",["Under ₹500","₹500–₹1,000","₹1,000–₹2,000","₹2,000–₹3,500","Above ₹3,500","Custom budget"]],["preferences","What should it include?",["Flowers","Chocolates","Snacks","Self-care","Personalised keepsake","Plant","Stationery","Other"]],["style","Choose a style",["Elegant","Romantic","Colourful","Minimal","Premium","Fun","Traditional"]]];
 function submit(e:FormEvent){e.preventDefault();const next:Record<string,string>={};if(!data.name&&kind!=="delivery")next.name="Please enter your name.";if(!data.phone)next.phone="Please enter a mobile number.";if(data.phone&&!/^\+?(?:91)?[6-9]\d{9}$/.test(data.phone.replace(/[\s()-]/g,"")))next.phone="Enter a valid Indian mobile number.";if(kind==="corporate"&&(!data.email||!data.email.includes("@")))next.email="Enter a valid work email.";setErrors(next);if(Object.keys(next).length)return;setStatus("loading");setTimeout(()=>setStatus("success"),900)}
 if(status==="success")return <div className="form-success" role="status"><span>✓</span><h2>Request prepared in this demo</h2><p>No information was transmitted. A production site can connect this reusable form to email, Google Sheets, Supabase or a CRM.</p><a className="button" href={whatsapp(`Hello Petal & Parcel,\n\nI would like to submit a ${kind} enquiry:\n${Object.entries(data).map(([k,v])=>`${k}: ${v}`).join("\n")}\n\nPlease confirm the next steps.`)} target="_blank" rel="noreferrer">Continue on WhatsApp</a><button onClick={()=>{setStatus("idle");setData({});setStep(0)}}>Start another request</button></div>;
 if(multi){const isDetails=step===customSteps.length;return <form className="smart-form builder" onSubmit={submit} noValidate><div className="progress"><span style={{width:`${((step+1)/(customSteps.length+1))*100}%`}}/></div><p className="step-count">Step {step+1} of {customSteps.length+1}</p>{!isDetails? <><h2>{customSteps[step][1]}</h2><div className="choice-grid">{(customSteps[step][2] as string[]).map(x=><button type="button" className={data[customSteps[step][0] as string]===x?"selected":""} onClick={()=>setData({...data,[customSteps[step][0] as string]:x})} key={x}>{x}</button>)}</div><div className="form-nav"><button type="button" disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button type="button" className="button" disabled={!data[customSteps[step][0] as string]} onClick={()=>setStep(step+1)}>Continue →</button></div></>:<><h2>Delivery and contact details</h2><FormFields data={data} setData={setData} errors={errors} fields={[["name","Your name","text"],["phone","Mobile / WhatsApp number","tel"],["area","Delivery area","text"],["date","Preferred date","date"],["request","Additional request","textarea"]]}/><div className="builder-summary"><h3>Your custom gift brief</h3>{customSteps.map(s=><p key={s[0] as string}><b>{s[1]}</b>{data[s[0] as string]}</p>)}</div><label className="consent"><input type="checkbox" required/> I agree to be contacted about this enquiry.</label><div className="form-nav"><button type="button" onClick={()=>setStep(step-1)}>Back</button><button className="button" disabled={status==="loading"}>{status==="loading"?"Preparing…":"Prepare WhatsApp request"}</button></div></>}</form>}
 return <form className="smart-form" onSubmit={submit} noValidate><h2>{kind==="corporate"?"Corporate quotation request":kind==="flower"?"Custom bouquet request":kind==="contact"?"Send an enquiry":"Delivery availability request"}</h2><FormFields data={data} setData={setData} errors={errors} fields={fields}/><label className="consent"><input type="checkbox" required/> I agree to be contacted about this enquiry.</label><label className="honeypot">Website<input tabIndex={-1} autoComplete="off"/></label><button className="button full" disabled={status==="loading"}>{status==="loading"?"Preparing your request…":"Prepare enquiry"}</button><p className="form-disclaimer">Demo submission mode: nothing is transmitted. Files stay in this browser session and require storage integration for production. Continue on WhatsApp after reviewing the prepared request.</p></form>}

function FormFields({data,setData,errors,fields}:{data:Record<string,string>;setData:(d:Record<string,string>)=>void;errors:Record<string,string>;fields:string[][]}){const min=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().split("T")[0];return <div className="form-grid">{fields.map(([name,label,type])=><label key={name} className={type==="textarea"||type==="file"?"wide":""}>{label}{type!=="file"&&<span>*</span>}{type==="textarea"?<textarea rows={4} value={data[name]||""} onChange={e=>setData({...data,[name]:e.target.value})}/>:type==="select"?<select value={data[name]||""} onChange={e=>setData({...data,[name]:e.target.value})}><option value="">Select</option><option>Yes</option><option>No</option><option>Not sure</option></select>:type==="file"?<><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>setData({...data,[name]:e.target.files?.[0]?.name||""})}/><small>JPG, PNG or PDF · interface demo only, not permanently uploaded</small></>:<input type={type} min={type==="date"?min:undefined} value={data[name]||""} onChange={e=>setData({...data,[name]:e.target.value})} aria-invalid={!!errors[name]}/>} {errors[name]&&<small role="alert">{errors[name]}</small>}</label>)}</div>}

export function FAQ({items=faqs}:{items?:string[][]}){return <div className="faq">{items.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div>}
export function PageHero({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <section className="page-hero"><div className="wrap"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></section>}
export function FinalCTA(){return <section className="final-cta"><div className="wrap"><div className="final-cta-copy"><span className="eyebrow light">A little help goes a long way</span><h2>Need help creating the perfect gift?</h2><p>Tell us the person, the moment and your budget. We’ll help with the rest.</p></div><div className="final-cta-actions"><a className="button light-button" href={whatsapp("Hello Petal & Parcel, I need help creating the perfect gift.")} target="_blank" rel="noreferrer">Ask on WhatsApp</a><Link className="button outline-light" href="/custom-gift">Build a custom gift</Link><a className="text-call" href={`tel:${business.phone.replace(/\s/g,"")}`}>Call {business.phone}</a></div></div></section>}
